# Generated by Django 4.2.5 on 2023-09-20 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('cla_cod', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
                ('cla_name', models.CharField(max_length=100)),
                ('descrip', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cli_cod', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
                ('cli_name', models.CharField(max_length=100)),
                ('cli_direc', models.CharField(max_length=100)),
                ('cli_telf_1', models.IntegerField(max_length=9)),
                ('cli_telf_2', models.IntegerField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('prod_cod', models.BigIntegerField(max_length=15, primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField()),
                ('clasificacion_cod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.clasificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('prov_cod', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
                ('prov_name', models.CharField(max_length=100)),
                ('prov_direc', models.CharField(max_length=100)),
                ('prov_telf', models.IntegerField(max_length=9)),
                ('prov_url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('nro_fac', models.BigIntegerField(max_length=15, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descuento', models.FloatField()),
                ('cantidad', models.IntegerField()),
                ('monto', models.FloatField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.cliente')),
                ('producto_cod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.proveedor'),
        ),
    ]
